### ISSUE TITLE
QR Code NOT Displayed Correctly

### ISSUE THREAD

**Issue by otamago** [nighthawk-apps/zcash-explorer#11]
**Describe the bug**
A clear and concise description of what the bug is. QR code of address is not displayed in the UI due to Content Security Policy directive violation.

**To Reproduce**
1. Go to ['/address/xxx'](https://zcashblockexplorer.com/address/t1XDLKrYbhwGYmgUaM4yWa4w8d1wb8s8zFq)
2. See error: QR code not displayed correctly. Tested on Brave Browser (v1.32.106 Chromium: 96.0.4664.45) and Firefox (v94.0)

![Screenshot from 2021-11-19 15-14-39](https://user-images.githubusercontent.com/77098373/142589078-5a35bc1d-f6fc-4d5a-9367-7ce82b383160.png)

**Comment by vamsiikrishna** [comment]
Thanks for reporting this !

**Comment by vamsiikrishna** [comment]
fixed ..

here's the link to the commit https://github.com/nighthawk-apps/zcash-explorer/commit/ebe29151e69682803a613191a757f7b49512ec7a


Thanks again for reporting the bug !
