### ISSUE TITLE
View Raw Transaction

### ISSUE THREAD

**Issue by dconnolly** [nighthawk-apps/zcash-explorer#16]
**Is your feature request related to a problem? Please describe.**

On some block explorers I'm able to view the raw transaction as a parsed, pretty-printed JSON blob (and hex):

<img width="204" alt="image" src="https://user-images.githubusercontent.com/552961/171180168-236c04ea-ca46-4317-9521-907fd29194cc.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/552961/171180321-d7850a23-d3b8-4f7b-bf2d-7f9615f636e5.png">

**Describe the solution you'd like**

It would be useful for me to have a link like this on Zcash Explorer when viewing transaction details.

**Describe alternatives you've considered**
I don't see a way to get this information from Zcash Explorer either explicitly as a feature or by some XHR/ API endpoint that I could inspect.

**Comment by vamsiikrishna** [comment]
Thank you suggesting this feature @dconnolly . It's now live.


![Screenshot 2022-06-03 170651](https://user-images.githubusercontent.com/554887/171846406-17ddefed-0452-4b78-8b6c-748ee283b525.png)


 We can just add ` /raw` to any valid TX URL on the explorer and get the JSON.
