### ISSUE TITLE
Internal Server Error for Shielded Transaction Page

### ISSUE THREAD

**Issue by luckytokidoki** [nighthawk-apps/zcash-explorer#18]
**To Reproduce**
1. Go to ['a shielded transaction page'](https://zcashblockexplorer.com/transactions/06e46cb49dec87916dd826fa2ea34bbb64b26f5f82a037bb66071f5683a6f750)
2. See error

**Screenshots**
![Screenshot from 2022-06-24 13-07-07](https://user-images.githubusercontent.com/77098373/175473278-529f07ed-b791-4dbb-acb0-f2b28e51d6b4.png)

**Platform:**
 - OS: Ubuntu 20.04
 - Browser v1.40.105 Chromium v103.0.5060.53

**Additional context**
Likely a problem with Orchard transactions or server error due to recent spike in shielded transactions.

**Comment by vamsiikrishna** [comment]
This issue was fixed earlier.
