### ISSUE TITLE
Improve Label on Transactions Currently Tagged "Unknown"

### ISSUE THREAD

**Issue by michaelharms6010** [nighthawk-apps/zcash-explorer#31]
**Is your feature request related to a problem? Please describe.**
Many transactions in the block explorer are tagged as tx type "Unknown". This makes transaction lists less meaningful at a glance, and is alarming for a casual user.

**Describe the solution you'd like**
Ideally, these would be attractively tagged appropriately as "Shielding", "Deshielding", "Shielded", and (doubt this applies here) "Public".

**Describe alternatives you've considered**
I've none. I _have_ considered that my solution might be based on faulty assumptions about the transactions in question. 

**Additional context**
Here are some examples - all have Orchard actions, presumably that's relevant to this issue.

Shielding: https://zcashblockexplorer.com/transactions/c7eb2ac6252fd266a74f5266ed9c1e585571ae941901480053f7886330829dea
Shielded: https://zcashblockexplorer.com/transactions/504f75ba1d7f397216c425e11424ea740215b52e484b469a67dba7923074cbcd
Deshielding: https://zcashblockexplorer.com/transactions/2e6b1180f806af3b4e0b51604a4b846f881db3801a410486269bfda5cb39c716

**Comment by vamsiikrishna** [comment]
Thanks @michaelharms6010 for reporting with examples.. Fix has been pushed to address the issue. 

**Before :** 

![before](https://user-images.githubusercontent.com/554887/228146436-d45de9ae-f0a2-43a1-862c-8ae59a957d2d.png)


**After :**

![after](https://user-images.githubusercontent.com/554887/228146555-6f658ce1-5e1f-4dc8-8ec5-f7eb25c9502b.png)
