### ISSUE TITLE
Zcash Explorer enhancements

### ISSUE THREAD

**Issue by Dadybayo** [nighthawk-apps/zcash-explorer#5]
Great work, cool that such a tool added to the Zcash ecosystem

Zcash has credible blockchain data and it is important to show holders 

Some of this data can be borrowed from Blockchair, they have an API

Of course it would be cool to get that data ourselves without a third party API, but I think that's overkill at this stage 

1. Overview data 
  - price 
  - circulation 
  - market cap 
  - trading volume
  - dominance

2. Price charts 
  - 1 week/ 1 month / 1 year / All time
  - ROI vs BTC/USD 

3. 24h statistics
  - transactions 
  - average transactions fee with charts 1 month / 3 months / 1 year / all time
  - blocks 
  - avg.time between blocks 
  - hashrate 

4. Total data 
  - blocks (total + 24h) 
  - latest block 
  - height / hash / time / miner / transaction count 
  - outputs 
  - addresses 

5. Mempool 
  - transactions
  - transactions per second 
  - outputs 

6. All about Zcash blockchain 
  - blockchain size with charts 
  - network nodes 
  - latest block (n minutes ago) 
  - difficulty with charts 1 month / 3 months / 1 year / all time

**Comment by nighthawk24** [comment]
Thank you for your feedback. Our vision for the initial version of the block explorer was a minimal, light weight explorer accessible for mobile wallets too.

For a network overview and several features mentioned you've mentioned, check out https://www.zdash.info

We will consider your suggestions to accommodate them in a privacy preserving way in a future update.
